openapi: 3.1.0
info:
  version: 1.0.0
  title: Tracker of Water
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Tracker of Water app
tags:
  - name: Auth
    description: Auth operations with user.
  - name: Users
    description: Operations with User`s info.
  - name: Water
    description: Operations with information about water consumption.
servers:
  - url: 'https://dark-side-of-the-app01.onrender.com'
paths:
  /auth/signup:
    post:
      $ref: '../swagger/paths/auth/signup/post.yaml'
  /auth/signin:
    post:
      $ref: '../swagger/paths/auth/signin/post.yaml'
  /auth/signout:
    post:
      $ref: '../swagger/paths/auth/signout/post.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh/post.yaml'
  /users:
    get:
      $ref: '../swagger/paths/users/get.yaml'
    patch:
      $ref: '../swagger/paths/users/patch.yaml'
  /users/photo:
    post:
      $ref: '../swagger/paths/users/photo/post.yaml'
  /water/{id}:
    delete:
      $ref: '../swagger/paths/water/{id}/delete.yaml'
    patch:
      $ref: '../swagger/paths/water/{id}/patch.yaml'
  /water/day:
    get:
      $ref: '../swagger/paths/water/day/get.yaml'
  /water/month:
    get:
      $ref: '../swagger/paths/water/month/get.yaml'
  /water:
    post:
      $ref: '../swagger/paths/water/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
